/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.dialog;

import models.Address;

/**
 *
 * @author intel
 */
public class CreateVolatilAddress extends javax.swing.JPanel {

    private final boolean isDelivery;

    public CreateVolatilAddress(boolean isDelivery) {
        this.isDelivery = isDelivery;
        initComponents();
        activeFields();
        init();
    }

    public CreateVolatilAddress(boolean isDelivery, Address address) {
        this.isDelivery = isDelivery;
        initComponents();
        init();
        fillFields(address);
    }

    private void activeFields() {
        txtFirstName.setEnabled(true);
        txtLastName.setEnabled(true);
        txtDni.setEnabled(true);
        txtPhone.setEnabled(true);
        txtDepartment.setEnabled(true);
        txtProvince.setEnabled(true);
        txtDistrict.setEnabled(true);
        txtStreetAddress.setEnabled(true);
        txtZipCode.setEnabled(true);
        txtReference.setEnabled(true);
    }

    private void fillFields(Address address) {
        txtFirstName.setText(address.getFirstName());
        txtLastName.setText(address.getLastName());
        txtDni.setText(address.getDni());
        txtPhone.setText(address.getPhone());
        txtDepartment.setText(address.getDepartment());
        txtProvince.setText(address.getProvince());
        txtDistrict.setText(address.getDistrict());
        txtStreetAddress.setText(address.getStreetAddress());
        txtZipCode.setText(address.getZipCode());
        txtReference.setText(address.getReference());
    }

    private void init() {
        if (isDelivery) {
            txtFirstName.setVisible(true);
            txtLastName.setVisible(true);
            txtDni.setVisible(true);
            txtPhone.setVisible(true);
            txtDepartment.setVisible(true);
            txtProvince.setVisible(true);
            txtDistrict.setVisible(true);
            txtZipCode.setVisible(true);
            txtStreetAddress.setVisible(true);
            referenceScroll.setVisible(true);

            lbFirstName.setVisible(true);
            lbLastName.setVisible(true);
            lbDni.setVisible(true);
            lbTelephone.setVisible(true);
            lbDepartment.setVisible(true);
            lbProvince.setVisible(true);
            lbDistrict.setVisible(true);
            lbZipCode.setVisible(true);
            lbStreetAddress.setVisible(true);
            lbReference.setVisible(true);
        } else {
            txtFirstName.setVisible(true);
            txtLastName.setVisible(true);
            txtDni.setVisible(true);
            txtPhone.setVisible(true);
            txtDepartment.setVisible(false);
            txtProvince.setVisible(false);
            txtDistrict.setVisible(false);
            txtZipCode.setVisible(false);
            txtStreetAddress.setVisible(false);
            referenceScroll.setVisible(false);

            lbFirstName.setVisible(true);
            lbLastName.setVisible(true);
            lbDni.setVisible(true);
            lbTelephone.setVisible(true);
            lbDepartment.setVisible(false);
            lbProvince.setVisible(false);
            lbDistrict.setVisible(false);
            lbZipCode.setVisible(false);
            lbStreetAddress.setVisible(false);
            lbReference.setVisible(false);
        }
    }

    public Address getData() {
        Address address = new Address();
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String dni = txtDni.getText();
        String phone = txtPhone.getText();
        String department = txtDepartment.getText();
        String province = txtProvince.getText();
        String district = txtDistrict.getText();
        String streetAddress = txtStreetAddress.getText();
        String zipCode = txtZipCode.getText();
        String reference = txtReference.getText();

        address.setFirstName(firstName);
        address.setLastName(lastName);
        address.setDni(dni);
        address.setPhone(phone);
        address.setDepartment(department);
        address.setProvince(province);
        address.setDistrict(district);
        address.setStreetAddress(streetAddress);
        address.setZipCode(zipCode);
        address.setReference(reference);

        return address;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbZipCode = new javax.swing.JLabel();
        lbReference = new javax.swing.JLabel();
        referenceScroll = new javax.swing.JScrollPane();
        txtReference = new javax.swing.JTextArea();
        lbFirstName = new javax.swing.JLabel();
        lbDni = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        txtProvince = new javax.swing.JTextField();
        lbDistrict = new javax.swing.JLabel();
        lbLastName = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtStreetAddress = new javax.swing.JTextField();
        lbProvince = new javax.swing.JLabel();
        lbTelephone = new javax.swing.JLabel();
        lbDepartment = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtDepartment = new javax.swing.JTextField();
        txtDistrict = new javax.swing.JTextField();
        lbStreetAddress = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();

        lbZipCode.setText("Código Postal");

        lbReference.setText("Referencia");

        txtReference.setColumns(20);
        txtReference.setLineWrap(true);
        txtReference.setRows(3);
        txtReference.setEnabled(false);
        referenceScroll.setViewportView(txtReference);

        lbFirstName.setText("Nombre");

        lbDni.setText("Dni");

        txtZipCode.setEnabled(false);

        txtProvince.setEnabled(false);

        lbDistrict.setText("Distrito");

        lbLastName.setText("Apellido");

        txtPhone.setEnabled(false);

        txtDni.setEnabled(false);

        txtStreetAddress.setEnabled(false);

        lbProvince.setText("Provincia");

        lbTelephone.setText("Teléfono");

        lbDepartment.setText("Departamento");

        txtLastName.setEnabled(false);

        txtDepartment.setEnabled(false);

        txtDistrict.setEnabled(false);

        lbStreetAddress.setText("Dirección");

        txtFirstName.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lbLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lbReference, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(referenceScroll))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtStreetAddress))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(lbProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDni, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(lbTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDni, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbReference, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(referenceScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbDepartment;
    private javax.swing.JLabel lbDistrict;
    private javax.swing.JLabel lbDni;
    private javax.swing.JLabel lbFirstName;
    private javax.swing.JLabel lbLastName;
    private javax.swing.JLabel lbProvince;
    private javax.swing.JLabel lbReference;
    private javax.swing.JLabel lbStreetAddress;
    private javax.swing.JLabel lbTelephone;
    private javax.swing.JLabel lbZipCode;
    private javax.swing.JScrollPane referenceScroll;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtDistrict;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtProvince;
    private javax.swing.JTextArea txtReference;
    private javax.swing.JTextField txtStreetAddress;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
