/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.list;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import models.Category;
import models.Subcategory;
import ui.components.ActionButton;

/**
 *
 * @author intel
 */
public class SubcategoryListItem extends javax.swing.JPanel {

    private JList<? extends SubcategoryListItem> jlist;
    private Subcategory subcategory;
    private Category category;
    private int index;

    public SubcategoryListItem(Category category, Subcategory subcategory) {

        setOpaque(true);
        initComponents();
        this.subcategory = subcategory;
        this.category = category;
        init();
    }

    public void setJlist(JList<? extends SubcategoryListItem> jlist) {
        this.jlist = jlist;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    public ActionButton getButton() {
        return btnDelete;
    }

    private void init() {
        lbName.setText(subcategory.getName());
        btnDelete.setIcon(new FlatSVGIcon("resources/icon/delete.svg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        btnDelete = new ui.components.ActionButton(ActionButton.ERROR);

        lbName.setText("Nombre");

        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbName))
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        category.getSubcategories().remove(subcategory);
        DefaultListModel<SubcategoryListItem> model = (DefaultListModel) jlist.getModel();
        model.removeElement(this);
    }//GEN-LAST:event_btnDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.components.ActionButton btnDelete;
    private javax.swing.JLabel lbName;
    // End of variables declaration//GEN-END:variables
}
